spring:
  datasource:
    url: jdbc:hsqldb:mem:mavha-db
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
logging:
  level:
    org:
      springframework.web: info
      hibernate:
        type: DEBUG
    com.mavha: debug