spring:
  datasource:
    url: jdbc:hsqldb:mem:testdb
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true

logging:
  level:
    org:
      springframework.web: INFO
      hibernate:
        type:
          DEBUG